### ISSUE TITLE
Stats comes wrong

### ISSUE THREAD

**Issue by Georgi-Petkov** [expersso/OECD#12]
Hello, 
I'm not sure if I'm doing this the right way but I wanted to communicate the spurious results I'm getting with this great package "OECD".
I couldn't find the same numbers on OECD website so I don't really know if the numbers that I receive when using get_dataset are wrong or the data on the site is wrong.
By looking at the results I would say that for some reason for 2016, CHE (Switzerland) the numbers are padded with "000".
I would provide more info if needed, just let me know. 2georgipetkov@gmail.com

library(tidyverse)
library(OECD)
library(DT)

Search_for <- "migration" # type search word or term

search_dataset(Search_for, get_datasets()) %>% 
  DT::datatable()

dat_str <- get_data_structure("MIG") # check the structure of the data

dat_str[[3]] %>% 
  DT::datatable()

mig <- get_dataset("MIG",
                   start_time = 2007, end_time = 2016) # change time span for the data

mig %>%
  filter(VAR =="B21",GEN == "TOT",CO2 != "TOT") %>% 
  filter(COU == "CHE",obsTime == 2014) %>% 
  group_by(CO2,obsValue,obsTime) %>% 
  summarise(people=sum(obsValue)) %>% 
  arrange(desc(people))

# A tibble: 152 x 4
# Groups:   CO2, obsValue [152]
   CO2   obsValue obsTime   people
   <chr>    <dbl> <chr>      <dbl>
 1 DEU   14354000 2016    14354000
 2 ITA   11044000 2016    11044000
 3 FRA    8233000 2016     8233000
 4 PRT    5967000 2016     5967000
 5 ESP    3380000 2016     3380000
 6 POL    2775000 2016     2775000
 7 HUN    2585000 2016     2585000
 8 GBR    2062000 2016     2062000
 9 AUT    2035000 2016     2035000
10 ROU    1932000 2016     1932000
# ... with 142 more rows

**Comment by expersso** [comment]
I'm not seeing these results at all:

```
mig %>%
  filter(VAR =="B21", GEN == "TOT", CO2 != "TOT") %>%
  filter(COU == "CHE",obsTime == 2014) %>%
  group_by(CO2,obsValue,obsTime) %>%
  summarise(people=sum(obsValue)) %>%
  arrange(desc(people))
```

   CO2   obsValue obsTime people
   <chr>    <dbl> <chr>    <dbl>
 1 DEU      16853 2014     16853
 2 ITA      11518 2014     11518
 3 FRA       8988 2014      8988
 4 PRT       8542 2014      8542
 5 ESP       4853 2014      4853
 6 POL       3457 2014      3457
 7 HUN       3133 2014      3133
 8 GBR       2385 2014      2385
 9 SVK       2215 2014      2215
10 AUT       2029 2014      2029

It also seems strange to me that the `obsTime` in your output is 2016 even though you're filtering on 2014. Perhaps you're using an older version of the package:

```
> packageVersion("OECD")
[1] ‘0.2.3.999’
```

More likely, however, there may have been something wrong with the OECD api at the time you were running your code.

**Comment by Georgi-Petkov** [comment]
Thanks for the quick response. I'm sorry for the confusion because of the filter, I forgot to change it when I tried to locate the mistake. I installed the package again,  ran the code again and got the same huge numbers for CHE, 2016. Please don't get me wrong but I think I'm lucky when I get such huge mistakes that are easy to spot because if the deviation is small it could be impossible to see and then the whole point you are trying to make with a chart is invalid.

> packageVersion("OECD")
[1] ‘0.2.3.999’
> 
> migr %>%
+   filter(VAR =="B21",GEN == "TOT",CO2 != "TOT") %>%
+   filter(COU == "CHE",obsTime == 2016) %>%
+   group_by(CO2,obsValue,obsTime) %>%
+   summarise(people=sum(obsValue)) %>%
+   arrange(desc(people))
# A tibble: 152 x 4
# Groups:   CO2, obsValue [152]
   CO2   obsValue obsTime   people
   <chr>    <dbl> <chr>      <dbl>
 1 DEU   14354000 2016    14354000
 2 ITA   11044000 2016    11044000
 3 FRA    8233000 2016     8233000
 4 PRT    5967000 2016     5967000
 5 ESP    3380000 2016     3380000
 6 POL    2775000 2016     2775000
 7 HUN    2585000 2016     2585000
 8 GBR    2062000 2016     2062000
 9 AUT    2035000 2016     2035000
10 ROU    1932000 2016     1932000
# ... with 142 more rows

**Comment by expersso** [comment]
This is clearly an issue with the data in the OECD database, not the `OECD` package. E.g. compare the data below with the screenshot from the OECD website and confirm that they're identical:

![image](https://user-images.githubusercontent.com/7280464/51114330-4438ff80-1805-11e9-8578-0d94b3ce4a9a.png)


![image](https://user-images.githubusercontent.com/7280464/51114290-1b186f00-1805-11e9-91f7-6ce084ea64dd.png)

**Comment by Georgi-Petkov** [comment]
As I mentioned when I first raised the issue I couldn't verify whether the
problem comes from the database or the package OECD.
You are absolutely right, the problem lies in the database.
Thanks for helping in identifying this issue.

Georgi Petkov
