### ISSUE TITLE
Error in get_data_structure and get_dataset: no package called XML

### ISSUE THREAD

**Issue by KHrehova** [expersso/OECD#17]
Hi, 

I tried to install and use this package using R 3.6.2, RStudio 1.2.5033. 
When I tried to follow the vignette, I get errors when trying to use 
get_data_structure and get_dataset: 
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘XML’.

I searched CRAN but no package called XML seems to be currently available for installation. There is xml2 and XML2R. Can you give advice where I can find this missing package?

Best regards
KHrehova

**Comment by gueyenono** [comment]
There actually is a CRAN package called XML: https://cran.r-project.org/web/packages/XML/index.html

**Comment by KHrehova** [comment]
Thank you. I see. It is available for R>4.00 so RStudio did not show it for my R3.62. Maybe I need to update my R. 
Best regards
KHrehova
