### ISSUE TITLE
New get_dataset() not working for all series due to hardcoded 1.1

### ISSUE THREAD

**Issue by CubicTom** [expersso/OECD#31]
The new get_dataset() function for the new API has hardcoded 1.1 into the query url, but some queries seem to require different number.

For example, I would like to fetch this series: https://data-explorer.oecd.org/vis?fs%5b0%5d=Topic%2C1%7CEconomy%23ECO%23%7CLeading%20indicators%23ECO_LEA%23&pg=0&fc=Topic&bp=true&snb=1&vw=tb&df%5bds%5d=dsDisseminateFinalDMZ&df%5bid%5d=DSD_STES%40DF_CLI&df%5bag%5d=OECD.SDD.STES&df%5bvs%5d=4.1&pd=%2C&dq=.M.LI...AA...H&ly%5brw%5d=TIME_PERIOD&ly%5bcl%5d=REF_AREA&to%5bTIME_PERIOD%5d=false&lo=10&lom=LASTNPERIODS

The data query of which should be:

https://sdmx.oecd.org/public/rest/data/OECD.SDD.STES,DSD_STES@DF_CLI,4.1/.M.LI...AA...H?startPeriod=2023-05

However, get_dataset() adds 1.1 after the series name "OECD.SDD.STES,DSD_STES@DF_CLI", even though it should be 4.1. 

With 1.1, the query returns a 404.

The same issue applies to the structure query.

**Comment by expersso** [comment]
Thanks! Should be fixed now.
