### ISSUE TITLE
OECD pension statistics 

### ISSUE THREAD

**Issue by msh855** [expersso/OECD#4]
I am struggling to download pension statistics using the examples available. 

Here it is what I want to do: 

```
# download from OECD
dataset_id <- "PNN_new"

# get structure of the dataset and labels
dstruc <- get_data_structure(dataset_id) 

# 13 dimensions 
# id: APLANS --> Total, by pension plan type
# id: ADEF   --> Total, by definition type
# id: ACONT  --> Total all funds

# fileters 
#  - Investments in Bonds (VAR id: 1000) 
#  - Investment  in Bonds issued by public administration  (VAR id: 1270) 
#  - Mutual Funds --> Bills and Bonds   (VAR id: 1220) 

```
Given the filters above I am trying for example this:

```
filter_list<-list(c("DEU","FRA"), "APLANS", "ADEF", "ACONT", "1000")
get_dataset(dataset = dataset_id, filter = filter_list)

But it results into a bad request: 

```
```Error in rsdmx::readSDMX(url) : 
  HTTP request failed with status: 400 Bad Request


```

I also have a question of how to download all countries together. 

I got the dataset I need only through the alternative strategy you describe. But, good know how to make the more direct one to work as well.

**Comment by chriswidell** [comment]
Hi,

It appears that you are missing a required filter, in this case unit of measure which can be either NAT or USD. I to struggled with figuring this out but when thinking logically about it, if you don't provide a unit of measure you will have no values.

I changed your filter to all of the following and each works fine:
- filter_list<-list("APLANS", "ADEF", "ACONT", "1000","USD", c("DEU","FRA"))
- filter_list<-list("APLANS", "ADEF", "ACONT", "1000","NAT", c("DEU","FRA"))
- filter_list<-list("APLANS", "ADEF", "ACONT", "1000",c("NAT","USD"), c("DEU","FRA"))
df <-get_dataset(dataset = dataset_id, filter = filter_list)

There also appears to be some sort of required order to the different filters (probably the same order in which they are listed by dstruc$VAR_DESC).

To get the entire dataset I would probably download it using the alternative method as downloading it without any filters crashes my R session (might still work for you tough). My guess is that the API times out after a while.

Regards, 

Chris
