### ISSUE TITLE
<XMLInputError: XML content does not seem to be XML: ''> error

### ISSUE THREAD

**Issue by costasroum** [expersso/OECD#7]
the get_database function doesn't seem to work anymore. I am getting an error: <XMLInputError: XML content does not seem to be XML: ''>

Could this have something to do with the fact that OECD changed their stats page from http://stats.oecd.org/  to https://stats.oecd.org/? What should we do to fix this? Thanks, 

Costas

**Comment by expersso** [comment]
Yes, I was also experiencing this yesterday, but stats.oecd.org was down altogether at the time. It's now back up, and `get_dataset` is working as normal.
