### ISSUE TITLE
get_dataset() fails on request

### ISSUE THREAD

**Issue by nreigl** [expersso/OECD#8]
Probably related to #7 

Trying to run the example given in **Alternative data-acquisition strategy**

````
library(OECD)

df <- get_dataset("PATS_REGION",
                  filter = "PCT_A.INVENTORS.BEL+BE10.TOTAL+BIOTECH", 
                  pre_formatted = TRUE)
````

fails with 

````
<XMLInputError: XML content does not seem to be XML: ''>
````

Problem first emerged Saturday (16.06.2018) evening. 

```
sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Estonian_Estonia.1257  LC_CTYPE=Estonian_Estonia.1257    LC_MONETARY=Estonian_Estonia.1257 LC_NUMERIC=C                     
[5] LC_TIME=Estonian_Estonia.1257    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] OECD_0.2.2.999

loaded via a namespace (and not attached):
 [1] httr_1.3.1      compiler_3.4.4  rsdmx_0.5-11    plyr_1.8.4      R6_2.2.2        tools_3.4.4     RCurl_1.95-4.10 yaml_2.1.19     Rcpp_0.12.17   
[10] bitops_1.0-6    XML_3.98-1.11  

````

**Comment by migari77** [comment]
I am having the same issue! Any ideas what is happening? When running the same exact code some weeks ago it was working fine.

Extra content at the end of the document
<XMLParserErrorList: 1: Extra content at the end of the document
>
Error in data.frame(data_structure@concepts) : 
  trying to get slot "concepts" from an object of a basic class ("NULL") with no slots

**Comment by expersso** [comment]
I find this curious, because it's working fine for me. My hunch is that it's related to the OECD changing to https. Could it be that you're behind proxies and haven't set your https_proxy environmental variable, e.g.
Sys.setenv("https_proxy" = "https://abc@def.com:8080"?

**Comment by shloonee** [comment]
I must admit I cannot rule this completely out (running RStudio Server on Google Compute Engine) but I do not experience any difficulties getting other data from http or https sources.

**Comment by expersso** [comment]
Since I can't replicate the problem, you could try to install patch #9 by running `devtools::install_github("expersso/OECD#9)`. I've changed the scheme to `https` in all calls in that patch.

**Comment by shloonee** [comment]
`devtools::install_github("expersso/OECD#9")` helped fix the problem in my case. Thx a lot!

**Comment by nreigl** [comment]
Installing patch #9 solved the problem for me. Thanks a lot.
